version: "3.7"

networks:
  app-net:
    driver: bridge

services:
  nginx:
    container_name: nginx
    image: docker_nginx
    build:
      context: ./.docker/nginx
      dockerfile: Dockerfile
    tty: true
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
    depends_on:
      - app
    networks:
      - app-net

  redis:
    container_name: redis
    image: redis:alpine
    expose:
      - "6379"
    ports:
      - "6379:6379"
    volumes:
      - ./.docker/redis/data:/data
    networks:
      - app-net

  app:
    container_name: app
    image: docker_app
    build: .
    entrypoint: dockerize -template ./.docker/app/.env:.env -wait tcp://db:3306 -timeout 40s
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=root
      - DB_PASSWORD=root
    volumes:
      - .:/var/www
    tty: true
    depends_on:
      - db
    networks:
      - app-net

  db:
    container_name: db
    image: docker_db
    build:
      context: .docker/mysql
      dockerfile: Dockerfile
    command: --innodb-use-native-aio=0
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
    ports:
      - "3306:3306"
    volumes:
      - ./.docker/mysql/data:/var/lib/mysql
    tty: true
    networks:
      - app-net
